export const cities = [
    { name: "Mumbai", state: "Maharashtra" },
    { name: "Delhi", state: "Delhi" },
    { name: "Bengaluru", state: "Karnataka" },
    { name: "Hyderabad", state: "Telangana" },
    { name: "Chennai", state: "Tamil Nadu" },
    { name: "Kolkata", state: "West Bengal" },
    { name: "Pune", state: "Maharashtra" },
    { name: "Ahmedabad", state: "Gujarat" },
    { name: "Jaipur", state: "Rajasthan" },
    { name: "Surat", state: "Gujarat" },
    { name: "Lucknow", state: "Uttar Pradesh" },
    { name: "Kanpur", state: "Uttar Pradesh" },
    { name: "Nagpur", state: "Maharashtra" },
    { name: "Indore", state: "Madhya Pradesh" },
    { name: "Bhopal", state: "Madhya Pradesh" },
    { name: "Patna", state: "Bihar" },
    { name: "Ranchi", state: "Jharkhand" },
    { name: "Jamshedpur", state: "Jharkhand" },
    { name: "Dhanbad", state: "Jharkhand" },
    { name: "Gaya", state: "Bihar" },
    { name: "Varanasi", state: "Uttar Pradesh" },
    { name: "Prayagraj", state: "Uttar Pradesh" },
    { name: "Agra", state: "Uttar Pradesh" },
    { name: "Aligarh", state: "Uttar Pradesh" },
    { name: "Moradabad", state: "Uttar Pradesh" },
    { name: "Bareilly", state: "Uttar Pradesh" },
    { name: "Ghaziabad", state: "Uttar Pradesh" },
    { name: "Noida", state: "Uttar Pradesh" },
    { name: "Gurgaon", state: "Haryana" },
    { name: "Faridabad", state: "Haryana" },
    { name: "Rohtak", state: "Haryana" },
    { name: "Panipat", state: "Haryana" },
    { name: "Sonipat", state: "Haryana" },
    { name: "Karnal", state: "Haryana" },
    { name: "Ambala", state: "Haryana" },
    { name: "Yamunanagar", state: "Haryana" },
    { name: "Kurukshetra", state: "Haryana" },
    { name: "Sirsa", state: "Haryana" },
    { name: "Hisar", state: "Haryana" },
    { name: "Bhiwani", state: "Haryana" },
    { name: "Rewari", state: "Haryana" },
    { name: "Mahendragarh", state: "Haryana" },
    { name: "Narnaul", state: "Haryana" },
    { name: "Chandigarh", state: "Chandigarh" },
    { name: "Mohali", state: "Punjab" },
    { name: "Panchkula", state: "Haryana" }
] as const;

export type CityParams = {
    city: string;
};
